version: '2'
services:
    bookmanagement-mongodb:
        container_name: bookmanagement-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/bookManagement/mongodb/:/data/db/
